project_id = "rcxrkvwxlzwzrllwdwgz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.request-password-recovery]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.fetch-evolution-groups]
    verify_jwt = false
  [functions.upload-media]
    verify_jwt = false
