[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["NODE_OPTIONS=--max-old-space-size=4096 bun run build"]

[start]
cmd = "bun run preview"